artifact_uri: file:///F:/data_science_glow_up/new_projects/Baiscs/Telco-Churn-Prediction/mlflow_experiments_log/101023702026089801/312d0071ef154c8b9ce521b51df24f6d/artifacts
end_time: 1707544893511
entry_point_name: ''
experiment_id: '101023702026089801'
lifecycle_stage: active
run_id: 312d0071ef154c8b9ce521b51df24f6d
run_name: oversampled-XGBClassifier
run_uuid: 312d0071ef154c8b9ce521b51df24f6d
source_name: ''
source_type: 4
source_version: ''
start_time: 1707544890083
status: 3
tags: []
user_id: asus
