artifact_location: /home/dipan.banik@sapt.local/Dipan/Telco-Churn-Prediction/notebooks/churn_experiments/459665437333002086
creation_time: 1706529929760
experiment_id: '459665437333002086'
last_update_time: 1706529929760
lifecycle_stage: active
name: telco-churn-classification
