artifact_uri: file:///F:/data_science_glow_up/new_projects/Baiscs/Telco-Churn-Prediction/mlflow_experiments_log/101023702026089801/eafede9684144481abc019d440546b27/artifacts
end_time: 1707544867991
entry_point_name: ''
experiment_id: '101023702026089801'
lifecycle_stage: active
run_id: eafede9684144481abc019d440546b27
run_name: oversampled-RandomForestClassifier
run_uuid: eafede9684144481abc019d440546b27
source_name: ''
source_type: 4
source_version: ''
start_time: 1707544862448
status: 3
tags: []
user_id: asus
