artifact_uri: file:///F:/data_science_glow_up/new_projects/Baiscs/Telco-Churn-Prediction/mlflow_experiments_log/101023702026089801/b31c87aa03384ce5b5f8298fae2618cd/artifacts
end_time: 1707544841982
entry_point_name: ''
experiment_id: '101023702026089801'
lifecycle_stage: active
run_id: b31c87aa03384ce5b5f8298fae2618cd
run_name: original-XGBClassifier
run_uuid: b31c87aa03384ce5b5f8298fae2618cd
source_name: ''
source_type: 4
source_version: ''
start_time: 1707544837508
status: 3
tags: []
user_id: asus
