artifact_uri: file:///F:/data_science_glow_up/new_projects/Baiscs/Telco-Churn-Prediction/mlflow_experiments_log/716796248283090398/9d661244f8004ce2abf8cb233b153f5f/artifacts
end_time: 1707574564497
entry_point_name: ''
experiment_id: '716796248283090398'
lifecycle_stage: active
run_id: 9d661244f8004ce2abf8cb233b153f5f
run_name: smoted-RandomForestClassifier
run_uuid: 9d661244f8004ce2abf8cb233b153f5f
source_name: ''
source_type: 4
source_version: ''
start_time: 1707574552536
status: 3
tags: []
user_id: asus
