artifact_uri: /home/dipan.banik@sapt.local/Dipan/Telco-Churn-Prediction/notebooks/churn_experiments/459665437333002086/94382e0289ac43b1bdcec3c3a4a8e1b8/artifacts
end_time: 1706529936602
entry_point_name: ''
experiment_id: '459665437333002086'
lifecycle_stage: active
run_id: 94382e0289ac43b1bdcec3c3a4a8e1b8
run_name: Original-LogisticRegression
run_uuid: 94382e0289ac43b1bdcec3c3a4a8e1b8
source_name: ''
source_type: 4
source_version: ''
start_time: 1706529929930
status: 3
tags: []
user_id: dipan.banik
