artifact_uri: file:///F:/data_science_glow_up/new_projects/Baiscs/Telco-Churn-Prediction/mlflow_experiments_log/101023702026089801/e51a4bf22cb14aeb9595cb7caf776419/artifacts
end_time: 1707544822920
entry_point_name: ''
experiment_id: '101023702026089801'
lifecycle_stage: active
run_id: e51a4bf22cb14aeb9595cb7caf776419
run_name: original-RandomForestClassifier
run_uuid: e51a4bf22cb14aeb9595cb7caf776419
source_name: ''
source_type: 4
source_version: ''
start_time: 1707544817237
status: 3
tags: []
user_id: asus
