artifact_uri: file:///F:/data_science_glow_up/new_projects/Baiscs/Telco-Churn-Prediction/mlflow_experiments_log/101023702026089801/f407a090e1d1433eab5c5cf2a6f2880a/artifacts
end_time: 1707544862435
entry_point_name: ''
experiment_id: '101023702026089801'
lifecycle_stage: active
run_id: f407a090e1d1433eab5c5cf2a6f2880a
run_name: oversampled-LogisticRegression
run_uuid: f407a090e1d1433eab5c5cf2a6f2880a
source_name: ''
source_type: 4
source_version: ''
start_time: 1707544859027
status: 3
tags: []
user_id: asus
