artifact_location: file:///F:/data_science_glow_up/new_projects/Baiscs/Telco-Churn-Prediction/mlflow_experiments_log/716796248283090398
creation_time: 1707574331708
experiment_id: '716796248283090398'
last_update_time: 1707574331708
lifecycle_stage: active
name: telco-churn-classification
