artifact_uri: file:///F:/data_science_glow_up/new_projects/Baiscs/Telco-Churn-Prediction/mlflow_experiments_log/101023702026089801/6c07aa56d32841488dfbbb40aba617a0/artifacts
end_time: 1707544925801
entry_point_name: ''
experiment_id: '101023702026089801'
lifecycle_stage: active
run_id: 6c07aa56d32841488dfbbb40aba617a0
run_name: smoted-XGBClassifier
run_uuid: 6c07aa56d32841488dfbbb40aba617a0
source_name: ''
source_type: 4
source_version: ''
start_time: 1707544922172
status: 3
tags: []
user_id: asus
