artifact_location: file:///F:/data_science_glow_up/new_projects/Baiscs/Telco-Churn-Prediction/mlflow_experiments_log/0
creation_time: 1707574331639
experiment_id: '0'
last_update_time: 1707574331639
lifecycle_stage: active
name: Default
