artifact_uri: file:///F:/data_science_glow_up/new_projects/Baiscs/Telco-Churn-Prediction/mlflow_experiments_log/101023702026089801/a714b5e2e70244c2bfff11f6d63ff9a0/artifacts
end_time: 1707544896911
entry_point_name: ''
experiment_id: '101023702026089801'
lifecycle_stage: active
run_id: a714b5e2e70244c2bfff11f6d63ff9a0
run_name: smoted-LogisticRegression
run_uuid: a714b5e2e70244c2bfff11f6d63ff9a0
source_name: ''
source_type: 4
source_version: ''
start_time: 1707544893524
status: 3
tags: []
user_id: asus
