artifact_uri: /home/dipan.banik@sapt.local/Dipan/Telco-Churn-Prediction/mlflow_experiments_log/673920883807630480/b1fa3136e9a54b26b88c149e4ddc414b/artifacts
end_time: 1707481561568
entry_point_name: ''
experiment_id: '673920883807630480'
lifecycle_stage: active
run_id: b1fa3136e9a54b26b88c149e4ddc414b
run_name: smoted-XGBClassifier
run_uuid: b1fa3136e9a54b26b88c149e4ddc414b
source_name: ''
source_type: 4
source_version: ''
start_time: 1707481509613
status: 3
tags: []
user_id: dipan.banik
