artifact_uri: file:///F:/data_science_glow_up/new_projects/Baiscs/Telco-Churn-Prediction/mlflow_experiments_log/716796248283090398/d018a8bf39554090b5bfe552ec72cab2/artifacts
end_time: 1707574420885
entry_point_name: ''
experiment_id: '716796248283090398'
lifecycle_stage: active
run_id: d018a8bf39554090b5bfe552ec72cab2
run_name: undersampled-LogisticRegression
run_uuid: d018a8bf39554090b5bfe552ec72cab2
source_name: ''
source_type: 4
source_version: ''
start_time: 1707574414162
status: 3
tags: []
user_id: asus
