artifact_location: /home/dipan.banik@sapt.local/Dipan/Telco-Churn-Prediction/mlflow_experiments_log/673920883807630480
creation_time: 1707481286678
experiment_id: '673920883807630480'
last_update_time: 1707481286678
lifecycle_stage: active
name: telco-churn-classification
