artifact_location: file:///F:/data_science_glow_up/new_projects/Baiscs/Telco-Churn-Prediction/mlflow_experiments_log/101023702026089801
creation_time: 1707544811637
experiment_id: '101023702026089801'
last_update_time: 1707544811637
lifecycle_stage: active
name: telco-churn-classification
