artifact_uri: /home/dipan.banik@sapt.local/Dipan/Telco-Churn-Prediction/mlflow_experiments_log/673920883807630480/4db239fade3f4742b791cd9bd2e3715d/artifacts
end_time: 1707481413878
entry_point_name: ''
experiment_id: '673920883807630480'
lifecycle_stage: active
run_id: 4db239fade3f4742b791cd9bd2e3715d
run_name: oversampled-LogisticRegression
run_uuid: 4db239fade3f4742b791cd9bd2e3715d
source_name: ''
source_type: 4
source_version: ''
start_time: 1707481412005
status: 3
tags: []
user_id: dipan.banik
