artifact_uri: file:///F:/data_science_glow_up/new_projects/Baiscs/Telco-Churn-Prediction/mlflow_experiments_log/716796248283090398/35ec3565f16f443b82e7cd5af489d51c/artifacts
end_time: 1707574552504
entry_point_name: ''
experiment_id: '716796248283090398'
lifecycle_stage: active
run_id: 35ec3565f16f443b82e7cd5af489d51c
run_name: smoted-LogisticRegression
run_uuid: 35ec3565f16f443b82e7cd5af489d51c
source_name: ''
source_type: 4
source_version: ''
start_time: 1707574545388
status: 3
tags: []
user_id: asus
