artifact_uri: /home/dipan.banik@sapt.local/Dipan/Telco-Churn-Prediction/mlflow_experiments_log/673920883807630480/deca0dc3f3e542b3957587c7b2ff9133/artifacts
end_time: 1707481357429
entry_point_name: ''
experiment_id: '673920883807630480'
lifecycle_stage: active
run_id: deca0dc3f3e542b3957587c7b2ff9133
run_name: undersampled-RandomForestClassifier
run_uuid: deca0dc3f3e542b3957587c7b2ff9133
source_name: ''
source_type: 4
source_version: ''
start_time: 1707481355394
status: 3
tags: []
user_id: dipan.banik
