artifact_uri: /home/dipan.banik@sapt.local/Dipan/Telco-Churn-Prediction/notebooks/churn_experiments/459665437333002086/ea5a73510d6b45c6902aa2016b0bbdf6/artifacts
end_time: 1706530141357
entry_point_name: ''
experiment_id: '459665437333002086'
lifecycle_stage: active
run_id: ea5a73510d6b45c6902aa2016b0bbdf6
run_name: Undersampling-RandomForestClassifier
run_uuid: ea5a73510d6b45c6902aa2016b0bbdf6
source_name: ''
source_type: 4
source_version: ''
start_time: 1706530137637
status: 3
tags: []
user_id: dipan.banik
