artifact_uri: /home/dipan.banik@sapt.local/Dipan/Telco-Churn-Prediction/mlflow_experiments_log/673920883807630480/ed211ab23143489e8fbfec17dbb81851/artifacts
end_time: 1707481292170
entry_point_name: ''
experiment_id: '673920883807630480'
lifecycle_stage: active
run_id: ed211ab23143489e8fbfec17dbb81851
run_name: original-RandomForestClassifier
run_uuid: ed211ab23143489e8fbfec17dbb81851
source_name: ''
source_type: 4
source_version: ''
start_time: 1707481289755
status: 3
tags: []
user_id: dipan.banik
