artifact_uri: /home/dipan.banik@sapt.local/Dipan/Telco-Churn-Prediction/notebooks/churn_experiments/459665437333002086/6d6885b6ba3a4ad49bc2819ab5c8428a/artifacts
end_time: 1706530133023
entry_point_name: ''
experiment_id: '459665437333002086'
lifecycle_stage: active
run_id: 6d6885b6ba3a4ad49bc2819ab5c8428a
run_name: Original-XGBClassifier
run_uuid: 6d6885b6ba3a4ad49bc2819ab5c8428a
source_name: ''
source_type: 4
source_version: ''
start_time: 1706529958541
status: 3
tags: []
user_id: dipan.banik
