artifact_uri: file:///F:/data_science_glow_up/new_projects/Baiscs/Telco-Churn-Prediction/mlflow_experiments_log/716796248283090398/8bbe367c1fe94734953dd7bdce2e6750/artifacts
end_time: 1707574459743
entry_point_name: ''
experiment_id: '716796248283090398'
lifecycle_stage: active
run_id: 8bbe367c1fe94734953dd7bdce2e6750
run_name: oversampled-LogisticRegression
run_uuid: 8bbe367c1fe94734953dd7bdce2e6750
source_name: ''
source_type: 4
source_version: ''
start_time: 1707574452851
status: 3
tags: []
user_id: asus
