artifact_uri: file:///F:/data_science_glow_up/new_projects/Baiscs/Telco-Churn-Prediction/mlflow_experiments_log/101023702026089801/27a1efa16e9b41388db45d3ff2bfef5b/artifacts
end_time: 1707544837487
entry_point_name: ''
experiment_id: '101023702026089801'
lifecycle_stage: active
run_id: 27a1efa16e9b41388db45d3ff2bfef5b
run_name: original-SVC
run_uuid: 27a1efa16e9b41388db45d3ff2bfef5b
source_name: ''
source_type: 4
source_version: ''
start_time: 1707544822934
status: 3
tags: []
user_id: asus
