artifact_uri: file:///F:/data_science_glow_up/new_projects/Baiscs/Telco-Churn-Prediction/mlflow_experiments_log/716796248283090398/6f925c5caa4747239d2dbfdf5dda66fa/artifacts
end_time: 1707574363682
entry_point_name: ''
experiment_id: '716796248283090398'
lifecycle_stage: active
run_id: 6f925c5caa4747239d2dbfdf5dda66fa
run_name: original-RandomForestClassifier
run_uuid: 6f925c5caa4747239d2dbfdf5dda66fa
source_name: ''
source_type: 4
source_version: ''
start_time: 1707574351863
status: 3
tags: []
user_id: asus
