artifact_uri: file:///F:/data_science_glow_up/new_projects/Baiscs/Telco-Churn-Prediction/mlflow_experiments_log/101023702026089801/fb21c88fa44a4e6b90511a69a7c0e652/artifacts
end_time: 1707544890071
entry_point_name: ''
experiment_id: '101023702026089801'
lifecycle_stage: active
run_id: fb21c88fa44a4e6b90511a69a7c0e652
run_name: oversampled-SVC
run_uuid: fb21c88fa44a4e6b90511a69a7c0e652
source_name: ''
source_type: 4
source_version: ''
start_time: 1707544868006
status: 3
tags: []
user_id: asus
