artifact_uri: file:///F:/data_science_glow_up/new_projects/Baiscs/Telco-Churn-Prediction/mlflow_experiments_log/101023702026089801/d89a94b686944b4d8eba23a966be67d2/artifacts
end_time: 1707544855559
entry_point_name: ''
experiment_id: '101023702026089801'
lifecycle_stage: active
run_id: d89a94b686944b4d8eba23a966be67d2
run_name: undersampled-SVC
run_uuid: d89a94b686944b4d8eba23a966be67d2
source_name: ''
source_type: 4
source_version: ''
start_time: 1707544849461
status: 3
tags: []
user_id: asus
