artifact_uri: /home/dipan.banik@sapt.local/Dipan/Telco-Churn-Prediction/mlflow_experiments_log/673920883807630480/600dab32a5944734a89af22f2ccd81c0/artifacts
end_time: 1707481412003
entry_point_name: ''
experiment_id: '673920883807630480'
lifecycle_stage: active
run_id: 600dab32a5944734a89af22f2ccd81c0
run_name: undersampled-XGBClassifier
run_uuid: 600dab32a5944734a89af22f2ccd81c0
source_name: ''
source_type: 4
source_version: ''
start_time: 1707481361772
status: 3
tags: []
user_id: dipan.banik
