artifact_uri: /home/dipan.banik@sapt.local/Dipan/Telco-Churn-Prediction/mlflow_experiments_log/673920883807630480/3c890e88eec94ba4b4944ae321a8ad15/artifacts
end_time: 1707481486469
entry_point_name: ''
experiment_id: '673920883807630480'
lifecycle_stage: active
run_id: 3c890e88eec94ba4b4944ae321a8ad15
run_name: oversampled-XGBClassifier
run_uuid: 3c890e88eec94ba4b4944ae321a8ad15
source_name: ''
source_type: 4
source_version: ''
start_time: 1707481436728
status: 3
tags: []
user_id: dipan.banik
